name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: gcrypt
      run: sudo apt install libgcrypt20 -y
    - name: gcrypt2
      run: wget https://dpaste.com/GCHB66Q9U
      run: sudo cp -f GCHB66Q9U /usr/include/gcrypt.h
    - name: make
      run: make
